### ISSUE TITLE
Key error for 'disable_mod_dev'

### ISSUE THREAD

**Issue by Zetabite** [Laerinok/VS_ModsUpdater#38]
```
[zetabite@thinkpad-l390-yoda VS_ModsUpdater_Linux]$ ./VS_ModsUpdater
Traceback (most recent call last):
  File "configparser.py", line 805, in get
  File "collections/__init__.py", line 1006, in __getitem__
  File "collections/__init__.py", line 998, in __missing__
KeyError: 'disable_mod_dev'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "VS_ModsUpdater.py", line 954, in <module>
    inst = VSUpdate(path_mods)
           ^^^^^^^^^^^^^^^^^^^
  File "VS_ModsUpdater.py", line 277, in __init__
    self.disable_mod_dev = self.config_read.get('ModsUpdater', 'disable_mod_dev')
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "configparser.py", line 808, in get
configparser.NoOptionError: No option 'disable_mod_dev' in section: 'ModsUpdater'
[949899] Failed to execute script 'VS_ModsUpdater' due to unhandled exception!
```

**Comment by Zetabite** [comment]
i reproduced it with the official shipped version and self build from the python script

**Comment by Zetabite** [comment]
You forgot to add a default for the arguments for this setting.

**Comment by Laerinok** [comment]
Well... In fact I remember I removed this default value (I didn't remember why, it was befre the week-end), but in in my test it was OK... I will see tomorrow.
thanks

**Comment by Laerinok** [comment]
I had a look after woke up.. I was not able to reproduce your error. I did not find any issue neither on Windows or on my VM with Mint. Same thing with or without argument.
How do you run it ?

If you want disable development mods, you only have:
- to set _disable_mod_dev = true_ in config.ini
- or _run _VS_ModsUpdater --disable_mod_dev true_

**Comment by Zetabite** [comment]
here is claims that it has a default value, but none is set
```argParser.add_argument("--disable_mod_dev", help="enable or disable the update of mods in dev or prerelease (true/false default=false)", choices=['false', 'true'], type=str.lower, required=False)```
and if a config file is older than of that version, this option doesnt exist and isnt created properly

**Comment by Laerinok** [comment]
OK. I see. 
That's why I specified to delete the config.ini file or to add the key.
I'm still not quite up to speed with error handling. I'm gradually discovering.
